name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="eztools-$tag-${{ matrix.target }}"
          
          mkdir out
          git fetch --recurse-submodules

          for dir in "AppCompatCacheParser" "MFTECmd" "evtx"
          do
            cd $dir
            dotnet publish . --configuration Release --os linux --framework net6.0 --output out -p:PublishSingleFile=true --self-contained false
            mv out/* ../out
            cd -
          done

          # Pack files
          tar czvf "${release_name}.tar.gz" out

          # Delete output directory
          rm -r out

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          