name: Publish

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Create an incremental release
        uses: aurestic/incrementarl-create-release@master
        with:
          flag_branch: true
          message: Bump version
          prev_tag: 'v'
          update_odoo_module_version: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup dotnet 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Build
        shell: bash
        run: |
          tag=$(git tag --sort=committerdate | grep -E '[0-9]' | tail -1)
          release_name="eztools-$tag-${{ matrix.target }}"
          
          mkdir out

          for dir in "AppCompatCacheParser" "MFTECmd" "evtx" "AmcacheParser" "PECmd" "Prefetch" "RBCmd" "RECmd" "WxTCmd"
          do
            cd $dir
            dotnet publish . --configuration Release --os linux --framework net6.0 --output out --self-contained false
            mv out/* ../out
            cd -
          done

          # Pack files
          tar czvf "${release_name}.tar.gz" -C out .

          # Delete output directory
          rm -r out

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          